### ISSUE TITLE
CODE

### ISSUE THREAD

**Issue by AmitIsraeli** [OpenTexture/Paint3D#1]
hi guys love your work (: 
waiting for the code

**Comment by IkuStudies** [comment]
me too, looking forward to testing

**Comment by Zzlongjuanfeng** [comment]
Hi, we are currently organizing the relevant code and will release it as soon as possible. Thank you for your attention.

**Comment by Zhengxinyang** [comment]
> Hi, we are currently organizing the relevant code and will release it as soon as possible. Thank you for your attention.

Is there an expected time?

**Comment by Samge0** [comment]
+1

**Comment by mulinAi** [comment]
+1, looking forward to

**Comment by kuaiqushangzixiba** [comment]
+1

**Comment by jiakechong1991** [comment]
+1

**Comment by HughLio** [comment]
+1

**Comment by wsb951** [comment]
+1

**Comment by jiangwei007** [comment]
+1

**Comment by Pamogar** [comment]
+1

**Comment by g0g5** [comment]
+1

**Comment by ccdle12** [comment]
+1

**Comment by wqdong8** [comment]
Great work! 
Is there any plan to release training data?

**Comment by jayvaghasiya** [comment]
+1

**Comment by fighting-zeng** [comment]
Plan when to open source code

**Comment by fighting-zeng** [comment]
Amazing job!
When do you plan to open source the code? Is there a planned schedule? @Zzlongjuanfeng

**Comment by fanyangpku** [comment]
+1

**Comment by ForrestPi** [comment]
will you plan to release the code?

**Comment by dqj5182** [comment]
Will the code be released?

**Comment by Zzlongjuanfeng** [comment]
Thank you for your attention,  Zhongqi @qzq2514 has cleaned and uploaded the code.
