### ISSUE TITLE
Image-conditioned model rarely condition on image

### ISSUE THREAD

**Issue by dqj5182** [OpenTexture/Paint3D#12]
I have run Paint3D in my own data, and I think image-conditioned model rarely get conditional input from image (not as pipeline perspective, but in the perspective of the final output).

May I ask how we can put more emphasis on image condition rather than text condition?

**Comment by samiede** [comment]
Decrease the denoising strength

**Comment by dqj5182** [comment]
@Zzlongjuanfeng Thanks for your feedback! Sorry but where can I increase the weight of image condition?

**Comment by Zzlongjuanfeng** [comment]
> @Zzlongjuanfeng Thanks for your feedback! Sorry but where can I increase the weight of image condition?

During class initialization, you can set the weight of the IP adapter using 'pipeline.set_ip_adapter_scale(xx)'.

**Comment by dqj5182** [comment]
Thanks a lot! I think my issue have been solved, so I will close the issue.
