### ISSUE TITLE
What does the number mean in the prompt?

### ISSUE THREAD

**Issue by iris112358** [OpenTexture/Paint3D#25]
Hi, thanks for open-sourcing this awesome work. I noticed that in the prompt (e.g., `UV map, (Sci-Fi digital painting:1.3), high quality, best quality`), there are numbers such as `1.3`. I'm wondering what does it mean? How can we write correct prompt to use the model?

**Comment by Zzlongjuanfeng** [comment]
It is used to emphasize prompts. You can find more details on its usage [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features).

**Comment by iris112358** [comment]
Got it. Thanks for the quick reply!
