### ISSUE TITLE
Runaway SD weights are removed from hugging face

### ISSUE THREAD

**Issue by mrtpk** [OpenTexture/Paint3D#28]
Hi Team,

Thank you for sharing your work. I was trying to run sample commands and found that the stable diffusion URLs were not working. On further digging, I understood that the weights were removed from hugging face. Can we use your work with other models instead of  runway's stable diffusion? Any guidance is very much appreciated.

Ref - https://www.reddit.com/r/StableDiffusion/comments/1f4epto/runway_took_down_15_and_15_inpainting/

As a quick work around, I changed SD value in yaml files to `"benjamin-paine/stable-diffusion-v1-5"`.

**Comment by Zzlongjuanfeng** [comment]
You can use the models from `benjamin-paine/stable-diffusion-v1-5`. I believe it serves as a backup for Runway's models.

**Comment by mrtpk** [comment]
Thank you for your comment. I changed the repo name and got it working.
