### ISSUE TITLE
Missing field in model_key

### ISSUE THREAD

**Issue by windshear55** [OpenTexture/Paint3D#3]
Hi,

Excellent works! It seems that the model_keys in config files are not correct, especially some personal model such as: `xxx/realisticVisionV13_v13_cvt`. Could you update the correct keys or upload these models?

**Comment by Zzlongjuanfeng** [comment]
The realisticVisionV13_v13 model is available on Hugging Face at this link: https://huggingface.co/justin759/realisticVisionV13_v13.safetensors. You can download it first and then convert it using the `tools/convert_original_stable_diffusion_to_diffusers.py` script.

**Comment by samiede** [comment]
The key in the config has the `cvt` ending, which suggest custom training, the one that you linked doesn't seem to be custom trained, is the model choice here important? Or can we just use any sd1.5 based model?

**Comment by Euron-ZC** [comment]
Excuse me, I wonder where can I find the **uvpos_cvt** in UV_based_inpaint_template config file? Thank you!

**Comment by qzq2514** [comment]
You can find the model from https://huggingface.co/GeorgeQi/Paint3d_UVPos_Control

**Comment by qzq2514** [comment]
> Excuse me, I wonder where can I find the **uvpos_cvt** in UV_based_inpaint_template config file? Thank you!

You can find the model from https://huggingface.co/GeorgeQi/Paint3d_UVPos_Control

**Comment by Zzlongjuanfeng** [comment]
> The key in the config has the `cvt` ending, which suggest custom training, the one that you linked doesn't seem to be custom trained, is the model choice here important? Or can we just use any sd1.5 based model?

You can choose any SD1.5-based model here; some models may work better for specific styles.
