### ISSUE TITLE
Image-condition texturing pipeline

### ISSUE THREAD

**Issue by windshear55** [OpenTexture/Paint3D#4]
Hi,

Nice work! I wonder how to run the image-to-3D pipeline as mentioned in the paper. Could you upload the model config for it or provide some instruction?

**Comment by HarryWang355** [comment]
I have the same question. I filled in the "condition_image_path" in the config file but it didn't seem to be doing anything...

**Comment by Zzlongjuanfeng** [comment]
Hi,
The image condition has been updated. It is implemented via the IP-adapter(https://github.com/tencent-ailab/IP-Adapter).
