### ISSUE TITLE
config model path

### ISSUE THREAD

**Issue by jh27kim** [OpenTexture/Paint3D#7]
Hi, thank you for sharing your work ! 

Could you please tell us which paths / arguments exactly should we input the .config fiels ? 

Thanks

**Comment by DenisKochetov** [comment]
> Hi, thank you for sharing your work !
> 
> Could you please tell us which paths / arguments exactly should we input the .config fiels ?
> 
> Thanks
[config.zip](https://github.com/OpenTexture/Paint3D/files/15336620/config.zip)
Mind that you have to manually download realisticVisionV13_v13_cvt, convert to safetensors and add your own path in depth_based_inpaint_template.yaml. Other models will be downloaded.

**Comment by Zzlongjuanfeng** [comment]
Config file has been updated. Thank you for your attention.
